//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorAppointmentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointemt
    {
        public int id { get; set; }
        public System.DateTime app_date { get; set; }
        public Nullable<int> doctor_id { get; set; }
        public Nullable<int> client_id { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Doctor Doctor { get; set; }
    }
}
