//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorAppointmentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorSchedule
    {
        public int no_patients { get; set; }
        public string work_day { get; set; }
        public int doctor_id { get; set; }
    
        public virtual Doctor Doctor { get; set; }
    }
}
